
import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const[address,setAddress]=useState("")
  
  const getFunds=async()=>{
    try {
      const response=await fetch('api/getGoerli',{
        method:'POST',
        body:JSON.stringify({address}),
        headers:{
          'Content-Type':'application/json'
        }
      });
      if(!response.ok)  
      {return alert('Something went wrong in response ! ')}
      
      alert("Transaction initiated succesfully!") 
      
    } catch (err) {
      console.error(err)
      alert("Something went wrong in api! ")
    }
  } 
  
  const getValidation=async ()=>{
           try {
            const response=await fetch('api/getNftValidation',{
              method:'POST',
              body:JSON.stringify({address}),
              headers:{
                'Content-Type':'application/json'
              }
            });
            if(!response.ok)  
            { console.log(response)
              return alert('Validation unsuccesful!!')}
            else{
              alert("Validation succesful!!")
              getFunds()
              }
           } catch (err) {
            console.error(err)
           }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div
        style={{
          height: "100vh",
          width: "100vw",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}>
       <input type="text" value={address} onChange={(e)=>setAddress(e.target.value)} 
       placeholder="Enter your wallet address"/>
       <button onClick={getValidation}>Click to get Test Goerli</button>
    </div>
     
    </div>
  )
}
